#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileWeatherApp.Droid.Resource", IsApplication=true)]

namespace MobileWeatherApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::MobileWeatherApp.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int clearday = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int clearnight = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cloudy = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int DarkSky = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int fog = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hail = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Location = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int partlycloudyday = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int partlycloudynight = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rain = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sleet = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int snow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int thunderstorm = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int tornado = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int wind = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int AddPlaceBtn = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int CenterLayout = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int DaysOfTheWeekList = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int IconImage = 2131034131;
			
			// aapt resource value: 0x7f050005
			public const int ImageIcon = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int MyPlacesList = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int RemoveBtn = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int SearchButton = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int SearchResults = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int SearchText = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int TextAlerts = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int TextCurrentTemp = 2131034115;
			
			// aapt resource value: 0x7f050014
			public const int TextDay = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int TextHighTemp = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int TextLowTemp = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int TextPlace = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int TextSummary = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int Title = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int imageView1 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int layout = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Alerts = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DailyForecast = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomeScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MyPlace = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Place = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Search = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int WeeklyForecast = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int WeeklyForecastItem = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int search = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
